# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d632b903309ebe06710186137e9806cc55eb3c7d61481fec73af3c2422978d64551918d6b6b43c12d00c540eaaca5ede91c4fda0658fd93df3e8eeb030c81ae2

test:
  secret_key_base: cb9c61d262992a4c4094d35d976b8974f3998f20a3d49bc76f546f75c8b288fac3a1d01611d6d7c17615c59713b752c6cf187873c6d7b211e9c52433ac6d8668

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
